#
# analyzer_e03.conf ( Ref.: analyzer_2020_20M.conf )
#

UNPACK:		./param/UNPACK/unpacker.xml
DIGIT:		./param/DIGIT/digit_data_20201210.xml
CMAP:		./param/CMAP/channel_map_20201210.xml
DCGEO:		./param/DCGEO/DCGeomParam_E03_20201218
DCDRFT:		./param/DCDRFT/DCDriftParam_03085
DCTDC:		./param/DCTDC/DCTdcCalib_03085
HDPRM:		./param/HDPRM/HodoParam_e03_20201216_2
HDPHC:		./param/HDPHC/HodoPHCParam_20201214
USER:		./param/USER/user_e03.txt
BH2FLT:		./param/BH2FLT/BH2Filter.param
BH1MTH:		./param/BH1MTH/BH1Matching.param

FLDCALC:	0.75008
FLDNMR:		0.763143
FLDMAP:		./param/KURAMA/KuramaFieldMap_E07_20170907

PK18:		1.408
K18TM:		./param/K18TM/K18MatrixParam_20200528
